/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/schema.json
export type VideoCard = {
  _type: "videoCard";
  eyebrow?: string;
  title: string;
  wistiaId?: string;
  coverAlt: string;
};

export type TextLink = {
  _type: "textLink";
  label: string;
  href: string;
};

export type Stat = {
  _type: "stat";
  figure: string;
  label: string;
  body: string;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type RepresentativeCase = {
  _type: "representativeCase";
  cite: string;
  note?: string;
};

export type PracticeAreaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "practiceArea";
};

export type PracticeAreaTab = {
  _type: "practiceAreaTab";
  area: PracticeAreaReference;
  headline?: string;
  callout?: string;
  links?: Array<
    {
      _key: string;
    } & TextLink
  >;
};

export type Office = {
  _type: "office";
  name: string;
  badge?: string;
  street: string;
  cityStateZip: string;
  phone: string;
  hours?: string;
  directions?: string;
  map?: string;
  href?: string;
};

export type FeeColumn = {
  _type: "feeColumn";
  label: string;
  body: string;
};

export type Expectation = {
  _type: "expectation";
  title: string;
  blurb: string;
  detail?: string;
};

export type DeadlineFigure = {
  _type: "deadlineFigure";
  figure: string;
  unit: string;
  body: string;
};

export type CtaLink = {
  _type: "ctaLink";
  label: string;
  href: string;
};

export type AttorneyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "attorney";
};

export type AttorneyQuote = {
  _type: "attorneyQuote";
  text: string;
  attorney: AttorneyReference;
};

export type DeadlinesSection = {
  _type: "deadlinesSection";
  eyebrow?: string;
  heading: string;
  lead?: string;
  cta?: CtaLink;
  deadlines?: Array<
    {
      _key: string;
    } & DeadlineFigure
  >;
};

export type PracticeAreasSection = {
  _type: "practiceAreasSection";
  eyebrow?: string;
  heading: string;
  subheading?: string;
  tabs?: Array<
    {
      _key: string;
    } & PracticeAreaTab
  >;
  disclaimer: string;
  allHeading?: string;
  allLink?: TextLink;
  allAreas?: Array<
    {
      _key: string;
    } & PracticeAreaReference
  >;
};

export type FeesSection = {
  _type: "feesSection";
  heading: string;
  columns?: Array<
    {
      _key: string;
    } & FeeColumn
  >;
  quote?: AttorneyQuote;
  cta?: CtaLink;
  disclaimer: string;
};

export type AboutSection = {
  _type: "aboutSection";
  eyebrow?: string;
  heading: string;
  body: RichText;
  expectationsLabel?: string;
  expectations?: Array<
    {
      _key: string;
    } & Expectation
  >;
  quote?: AttorneyQuote;
  video?: VideoCard;
};

export type FeaturedCaseResultReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "featuredCaseResult";
};

export type CaseResultsSection = {
  _type: "caseResultsSection";
  heading: string;
  lead: string;
  link?: CtaLink;
  results?: Array<
    {
      _key: string;
    } & FeaturedCaseResultReference
  >;
  disclaimer: string;
};

export type Hero = {
  _type: "hero";
  eyebrow?: string;
  heading: string;
  headingAccent?: string;
  body?: string;
  buttons?: Array<
    {
      _key: string;
    } & CtaLink
  >;
};

export type FirmDetails = {
  _id: string;
  _type: "firmDetails";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  shortName: string;
  blurb?: string;
  phone: string;
  sms?: string;
  offices?: Array<
    {
      _key: string;
    } & Office
  >;
  advertisingLabel: string;
  legalDisclaimer: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PracticeArea = {
  _id: string;
  _type: "practiceArea";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  group:
    | "personal-injury"
    | "medical-malpractice"
    | "defective-medical-devices"
    | "employment-law"
    | "mass-torts";
  icon?:
    | "car"
    | "truck"
    | "motorcycle"
    | "slip"
    | "malpractice"
    | "construction"
    | "nursing"
    | "dog"
    | "premises"
    | "wrongfuldeath";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  blurb?: string;
  linkLabel?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Attorney = {
  _id: string;
  _type: "attorney";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  role: string;
  portrait: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  summary: string;
  quote?: string;
  headline?: string;
  biography: RichText;
  pullQuote?: string;
  barAdmissions?: Array<string>;
  education?: Array<string>;
  languages?: Array<string>;
  honors?: Array<string>;
  affiliations?: Array<string>;
  representativeCases?: Array<
    {
      _key: string;
    } & RepresentativeCase
  >;
  location?: string;
  phone?: string;
  fax?: string;
};

export type CaseResult = {
  _id: string;
  _type: "caseResult";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  recovered: string;
  category:
    | "Auto Accident"
    | "Motorcycle Accident"
    | "Truck Accident"
    | "Pedestrian Accident"
    | "Slip & Fall"
    | "Premises Liability"
    | "Construction Accident"
    | "Medical Malpractice"
    | "Traumatic Brain Injury"
    | "Personal Injury";
  summary: string;
};

export type FeaturedCaseResult = {
  _id: string;
  _type: "featuredCaseResult";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  recovered: string;
  insurerOffered: string;
  category:
    | "Auto Accident"
    | "Motorcycle Accident"
    | "Truck Accident"
    | "Pedestrian Accident"
    | "Slip & Fall"
    | "Premises Liability"
    | "Construction Accident"
    | "Medical Malpractice"
    | "Traumatic Brain Injury"
    | "Personal Injury";
  county: string;
  summary: string;
  clientName: string;
  quote: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  wistiaId?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: Hero;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  caseResults?: CaseResultsSection;
  about?: AboutSection;
  fees?: FeesSection;
  practiceAreas?: PracticeAreasSection;
  deadlines?: DeadlinesSection;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | VideoCard
  | TextLink
  | Stat
  | RichText
  | RepresentativeCase
  | PracticeAreaReference
  | PracticeAreaTab
  | Office
  | FeeColumn
  | Expectation
  | DeadlineFigure
  | CtaLink
  | AttorneyReference
  | AttorneyQuote
  | DeadlinesSection
  | PracticeAreasSection
  | FeesSection
  | AboutSection
  | FeaturedCaseResultReference
  | CaseResultsSection
  | Hero
  | FirmDetails
  | SanityImageAssetReference
  | PracticeArea
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Attorney
  | CaseResult
  | FeaturedCaseResult
  | HomePage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{    hero{      eyebrow,      heading,      headingAccent,      body,      buttons[]{ _key, label, href }    },    stats[]{ _key, figure, label, body },    caseResults{      heading,      lead,      link{ label, href },      disclaimer,      results[]->{        _id,        recovered,        insurerOffered,        category,        county,        clientName,        quote,        wistiaId,        image{ ..., alt }      }    },    about{      eyebrow,      heading,      body,      expectationsLabel,      expectations[]{ _key, title, blurb, detail },      quote{        text,        attorney->{ name, role, "slug": slug.current, portrait }      },      video{ eyebrow, title, wistiaId, coverAlt }    },    fees{      heading,      columns[]{ _key, label, body },      quote{        text,        attorney->{ name, role, "slug": slug.current, portrait }      },      cta{ label, href },      disclaimer    },    practiceAreas{      eyebrow,      heading,      subheading,      tabs[]{        _key,        headline,        callout,        links[]{ _key, label, href },        area->{          _id,          name,          "slug": slug.current,          icon,          linkLabel,          image{ ..., alt }        }      },      disclaimer,      allHeading,      allLink{ label, href },      allAreas[]->{ _id, name, "slug": slug.current }    },    deadlines{      eyebrow,      heading,      lead,      cta{ label, href },      deadlines[]{ _key, figure, unit, body }    }  }
export type HOME_PAGE_QUERY_RESULT =
  | {
      hero: null;
      stats: null;
      caseResults: null;
      about: null;
      fees: null;
      practiceAreas: null;
      deadlines: null;
    }
  | {
      hero: {
        eyebrow: string | null;
        heading: string;
        headingAccent: string | null;
        body: string | null;
        buttons: Array<{
          _key: string;
          label: string;
          href: string;
        }> | null;
      } | null;
      stats: Array<{
        _key: string;
        figure: string;
        label: string;
        body: string;
      }> | null;
      caseResults: {
        heading: string;
        lead: string;
        link: {
          label: string;
          href: string;
        } | null;
        disclaimer: string;
        results: Array<{
          _id: string;
          recovered: string;
          insurerOffered: string;
          category:
            | "Auto Accident"
            | "Construction Accident"
            | "Medical Malpractice"
            | "Motorcycle Accident"
            | "Pedestrian Accident"
            | "Personal Injury"
            | "Premises Liability"
            | "Slip & Fall"
            | "Traumatic Brain Injury"
            | "Truck Accident";
          county: string;
          clientName: string;
          quote: string;
          wistiaId: string | null;
          image: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt: string | null;
            _type: "image";
          };
        }> | null;
      } | null;
      about: {
        eyebrow: string | null;
        heading: string;
        body: RichText;
        expectationsLabel: string | null;
        expectations: Array<{
          _key: string;
          title: string;
          blurb: string;
          detail: string | null;
        }> | null;
        quote: {
          text: string;
          attorney: {
            name: string;
            role: string;
            slug: string;
            portrait: {
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              alt?: string;
              _type: "image";
            };
          };
        } | null;
        video: {
          eyebrow: string | null;
          title: string;
          wistiaId: string | null;
          coverAlt: string;
        } | null;
      } | null;
      fees: {
        heading: string;
        columns: Array<{
          _key: string;
          label: string;
          body: string;
        }> | null;
        quote: {
          text: string;
          attorney: {
            name: string;
            role: string;
            slug: string;
            portrait: {
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              alt?: string;
              _type: "image";
            };
          };
        } | null;
        cta: {
          label: string;
          href: string;
        } | null;
        disclaimer: string;
      } | null;
      practiceAreas: {
        eyebrow: string | null;
        heading: string;
        subheading: string | null;
        tabs: Array<{
          _key: string;
          headline: string | null;
          callout: string | null;
          links: Array<{
            _key: string;
            label: string;
            href: string;
          }> | null;
          area: {
            _id: string;
            name: string;
            slug: string;
            icon:
              | "car"
              | "construction"
              | "dog"
              | "malpractice"
              | "motorcycle"
              | "nursing"
              | "premises"
              | "slip"
              | "truck"
              | "wrongfuldeath"
              | null;
            linkLabel: string | null;
            image: {
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              alt: string | null;
              _type: "image";
            } | null;
          };
        }> | null;
        disclaimer: string;
        allHeading: string | null;
        allLink: {
          label: string;
          href: string;
        } | null;
        allAreas: Array<{
          _id: string;
          name: string;
          slug: string;
        }> | null;
      } | null;
      deadlines: {
        eyebrow: string | null;
        heading: string;
        lead: string | null;
        cta: {
          label: string;
          href: string;
        } | null;
        deadlines: Array<{
          _key: string;
          figure: string;
          unit: string;
          body: string;
        }> | null;
      } | null;
    }
  | null;

// Source: src/lib/queries.ts
// Variable: FIRM_DETAILS_QUERY
// Query: *[_id == "firmDetails"][0]{    name,    shortName,    blurb,    phone,    sms,    offices[]{      _key,      name,      badge,      street,      cityStateZip,      phone,      hours,      directions,      map,      href    },    advertisingLabel,    legalDisclaimer  }
export type FIRM_DETAILS_QUERY_RESULT =
  | {
      name: null;
      shortName: null;
      blurb: null;
      phone: null;
      sms: null;
      offices: null;
      advertisingLabel: null;
      legalDisclaimer: null;
    }
  | {
      name: string;
      shortName: null;
      blurb: null;
      phone: string | null;
      sms: null;
      offices: null;
      advertisingLabel: null;
      legalDisclaimer: null;
    }
  | {
      name: string;
      shortName: null;
      blurb: string | null;
      phone: null;
      sms: null;
      offices: null;
      advertisingLabel: null;
      legalDisclaimer: null;
    }
  | {
      name: string;
      shortName: string;
      blurb: string | null;
      phone: string;
      sms: string | null;
      offices: Array<{
        _key: string;
        name: string;
        badge: string | null;
        street: string;
        cityStateZip: string;
        phone: string;
        hours: string | null;
        directions: string | null;
        map: string | null;
        href: string | null;
      }> | null;
      advertisingLabel: string;
      legalDisclaimer: string;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "homePage"][0]{\n    hero{\n      eyebrow,\n      heading,\n      headingAccent,\n      body,\n      buttons[]{ _key, label, href }\n    },\n    stats[]{ _key, figure, label, body },\n    caseResults{\n      heading,\n      lead,\n      link{ label, href },\n      disclaimer,\n      results[]->{\n        _id,\n        recovered,\n        insurerOffered,\n        category,\n        county,\n        clientName,\n        quote,\n        wistiaId,\n        image{ ..., alt }\n      }\n    },\n    about{\n      eyebrow,\n      heading,\n      body,\n      expectationsLabel,\n      expectations[]{ _key, title, blurb, detail },\n      quote{\n        text,\n        attorney->{ name, role, "slug": slug.current, portrait }\n      },\n      video{ eyebrow, title, wistiaId, coverAlt }\n    },\n    fees{\n      heading,\n      columns[]{ _key, label, body },\n      quote{\n        text,\n        attorney->{ name, role, "slug": slug.current, portrait }\n      },\n      cta{ label, href },\n      disclaimer\n    },\n    practiceAreas{\n      eyebrow,\n      heading,\n      subheading,\n      tabs[]{\n        _key,\n        headline,\n        callout,\n        links[]{ _key, label, href },\n        area->{\n          _id,\n          name,\n          "slug": slug.current,\n          icon,\n          linkLabel,\n          image{ ..., alt }\n        }\n      },\n      disclaimer,\n      allHeading,\n      allLink{ label, href },\n      allAreas[]->{ _id, name, "slug": slug.current }\n    },\n    deadlines{\n      eyebrow,\n      heading,\n      lead,\n      cta{ label, href },\n      deadlines[]{ _key, figure, unit, body }\n    }\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_id == "firmDetails"][0]{\n    name,\n    shortName,\n    blurb,\n    phone,\n    sms,\n    offices[]{\n      _key,\n      name,\n      badge,\n      street,\n      cityStateZip,\n      phone,\n      hours,\n      directions,\n      map,\n      href\n    },\n    advertisingLabel,\n    legalDisclaimer\n  }\n': FIRM_DETAILS_QUERY_RESULT;
  }
}
